stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - pip3 install pipenv
    - pipenv install
    - export VENV_HOME_DIR=$(pipenv --venv)
    - source $VENV_HOME_DIR/bin/activate
    - python pinit/manage.py migrate
    
test:
  stage: test
  script:
    - export VENV_HOME_DIR=$(pipenv --venv)
    - source $VENV_HOME_DIR/bin/activate
    - python pinit/manage.py test
    
deploy:
  stage: deploy
  script:
    - dpl --provider=heroku --app=pin-it-app --api-key=$HEROKU_API_KEY