stages:
  - build
  - test
  
build:
  stage: build
  script:
    - pip3 install pipenv
    - pipenv install
    
test:
  stage: test
  script:
    - export VENV_HOME_DIR=$(pipenv --venv)
    - source $VENV_HOME_DIR/bin/activate
    - python pinit/manage.py test