language: python
services:
- postgresql
python:
- '3.6'

# install dependencies
before_install:
- pip install pipenv
install:
- pipenv install

# testing
before_script:
- psql -c 'CREATE DATABASE test_db;' -U postgres
env:
- DATABASE_URL=postgres://postgres@localhost/test_db
script:
- python manage.py test

# deploy to heroku
deploy:
  provider: heroku
  api_key:
    secure: HE/hpispnb7+4DeNyUqGkLl0rwNTxD6b2IbGX1XAIWsdlBMKXsWndva/c8CgodUisH8KgQvOeuoR4ByXEt2AsAfmioDOrpO/q4pvwx7b2zRivRMp6oX1/IlOHOp4IZfgIG0oM76ga7pDdxllhKoClo4jrqxUSLewNikl1KCe7PX7TT0r4DVYrz/MhPIfF5AJxWIxmwPayYPXOhzlbmNVnyJBSY1WbfPgz7H8wPiukJXfE3h4eZYGXPs7guL+aaUTdPHVI6WWtlKa/duD3MnyWW6JBRgLhORTvM97YogcTSgiRcmw9cRtBla1n96yoIaH4DbfR4UiEYBw7cNPbBDipmLAN5N/RF2hOI3BmKoe0GzMVtl4siYr2XJBLKPzXW97h3MrijQCNFmmcTrXg1xBV00DOt0BXqG+VqGieXyeeDhjsVsgcBwz9Y9Ivpot8QdG02OJTvs6veCzjz1ejT6utoyp9q7QkVKYMcLcKcvW+DQJLicWkDB2KpklweNfOmXYU9wDGMl7DNwlk3zHsTqNTOp6S8z35WfpTJvPNkD1bWDYunsO+zTgrcycap9n1IV17/k7URov7ejdC9HlzODZXDr2EAb/v+pR0EEinigsX2J9ZzCLoIMRVa4yrnsEXyx3LIkCvEaI67vRdXOaFbZoii2xociBIZe1uzBGTkpw2E4=
  app: pin-it-app
  on:
    repo: Pin-It/PinItServer
