language: python

services:
  - postgresql

python:
  - "3.6"

before_install:
  - pip install pipenv

install:
  - pipenv install

before_script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres

env:
  - DATABASE_URL=postgres://postgres@localhost/test_db

script:
  - python manage.py test