# Generated by Django 2.0.5 on 2018-05-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_type',
            field=models.IntegerField(choices=[(1, 'Pickpocket'), (2, 'Drunk'), (3, 'Robbery'), (4, 'Scam'), (5, 'Harassment'), (6, 'Others')]),
        ),
    ]
