# Generated by Django 2.0.5 on 2018-06-04 17:19

import api.middleware.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180602_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='by_user',
            field=models.ForeignKey(default=api.middleware.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='by_user',
            field=models.ForeignKey(default=api.middleware.current_user.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
